[18기 한지영] 강좌 리스트 뷰, 필터링 구현 완료 (+ unit test 완료)
wecode-bootcamp-korea/18-2nd-class200ok-backend pull request #22
Opened 2021-04-06 15:45 UTC by ziy0ung1234

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- pendinglecture list view 생성
- 카테고리 필터링 및 솔팅(최신순,인기순)
- 유닛테스트

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
### 강좌 리스트
- 달성률은 count 사용해서 구현(응원20개=100%달성)
- 리스트 뿌려줄때 디데이 부분 datetime과 timedelta 사용해서 구현
### 필터링
- 서브카테고리 같은 변수 여러개가 쿼리스트링으로 오도록 getlist사용
- Q사용해서 같은 변수의  value값이 중복 가능하도록 구현
###솔팅(최신순,인기순)
- 옵션을 딕셔너리로 묶음 + `-`를 붙여 내림차 순으로 정렬
- pending_classes변수에 필터링 거친 부분에서 오더바이로 솔팅

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
 솔팅부분  if문으로 오더바이 사용해서 두가지 경우 나눠 작성했다가 더 줄여볼 수가 있어서 줄였습니다! 승현님이 오늘 if문으로 사용해도 괜찮다고 하셨는데 줄이지 말고 다시 if문으로 쓰는게 나을까요? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-04-06 15:55 UTC, ziy0ung1234 commented
<img width="578" alt="스크린샷 2021-04-07 오전 12 54 59" src="https://user-images.githubusercontent.com/77558556/113740761-f5f0dd80-973b-11eb-8764-d24634021dfd.png">
<img width="810" alt="스크린샷 2021-04-07 오전 12 20 27" src="https://user-images.githubusercontent.com/77558556/113740768-f7baa100-973b-11eb-81d6-4b30837527bf.png">
<img width="810" alt="스크린샷 2021-04-07 오전 12 19 09" src="https://user-images.githubusercontent.com/77558556/113740778-f9846480-973b-11eb-8d87-0ff8b3289416.png">

2021-04-06 15:58 UTC, ziy0ung1234 commented
서브카테고리 필터링 localhost:8000/lecture?sub_category=3&sub_category=7
<img width="810" alt="스크린샷 2021-04-07 오전 12 19 09" src="https://user-images.githubusercontent.com/77558556/113741087-42d4b400-973c-11eb-85bc-1b8c29a4a0e2.png">

2021-04-06 15:59 UTC, ziy0ung1234 commented
필터링+솔팅(인기순) localhost:8000/lecture?sub_category=3&sub_category=7&sort=popular
<img width="810" alt="스크린샷 2021-04-07 오전 12 20 27" src="https://user-images.githubusercontent.com/77558556/113741241-67c92700-973c-11eb-93d4-12d34b07dfde.png">

2021-04-07 08:19 UTC, jamessoun93 requested changes

2021-04-07 08:19 UTC, jamessoun93 commented on lecture/views.py
> +            'dueDate'     : (date_now - (date_now+timedelta(days=15)).replace(tzinfo=None)).days #나와야하는 형식= 10
key 가 어떤건 camelCase고 어떤건 snake_case 인데 통일해주세요.

2021-04-07 08:19 UTC, jamessoun93 commented on lecture/views.py
> +            'dueDate'     : (date_now - (date_now+timedelta(days=15)).replace(tzinfo=None)).days #나와야하는 형식= 10
due_date는 첨부해주신 통신결과를 보니 `-15` 이런 형태로 리턴되는 것 같은데 무슨뜻인가요?

2021-04-07 08:19 UTC, jamessoun93 commented on lecture/views.py
> +            'creator'     : pending_class.user.creator_set.all().first().nickname,
first() 하실때 all() 굳이 필요없을텐데 테스트해보시고 불필요하다면 all 빼주세요!

2021-04-07 08:19 UTC, jamessoun93 commented on lecture/views.py
> +                q.add(Q(sub_category=sub_category), q.OR)
지영님 이 부분 field lookup `__` 사용하시면 더 가독성 좋고 쉽게 해결되는데 시도해보시겠어요?

2021-04-07 08:19 UTC, jamessoun93 commented on lecture/views.py
> +        }
sort good 👍

2021-04-07 08:19 UTC, jamessoun93 commented on lecture/views.py
> +            'achieveRate' : int((pending_class.vote__count/20)*100),
위에서 annotate 써서 vote count 를 종합하셨는데 굳이 vote__count 해주실 필요가 있을까요?

2021-04-07 12:30 UTC, ziy0ung1234 commented on lecture/views.py
> +            'dueDate'     : (date_now - (date_now+timedelta(days=15)).replace(tzinfo=None)).days #나와야하는 형식= 10
확인하고 수정했습니다!

2021-04-07 12:31 UTC, ziy0ung1234 commented on lecture/views.py
> +            'creator'     : pending_class.user.creator_set.all().first().nickname,
테스트 후 뺐습니다!

2021-04-08 08:05 UTC, jamessoun93 approved these changes

2021-04-08 08:05 UTC, merged